[build]
  command = "yarn install && mv node_modules/@ffmpeg/core/dist/* public/static/js && yarn build"

[[headers]]
  for = "/*"
  [headers.values]
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Embedder-Policy = "require-corp"
